// Generated by CoffeeScript 1.6.2
$(function() {
  if ($('#wrapper').length > 0) {
    return $('#wrapper').waypoint(function(dir) {
      if (dir === 'down') {
        return $('#sidebar').addClass('stick');
      } else {
        return $('#sidebar').removeClass('stick');
      }
    }, {
      offset: 30
    });
  }
});
